name: "checkout and build"
on:
  workflow_call:
    inputs:
      DATABASE_PASSWORD:
        description: 'required input'
        required: true
        type: string

      DATABASE_USER:
        description: 'required input'
        required: true
        type: string

      DATABASE_DB:
        description: 'required input'
        required: true
        type: string
    secrets:
      PAT:
        description: 'pat of gofr'
        required: true
jobs:
  postman-tests:
    name: 📝 Postman Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zopsmart/gha-images:go-0.1.0
      options: --rm
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}
    services:
      mysql:
        image: mysql:8.0.31
        env:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "zs_cloud_api"
        ports:
          - 3306:3306
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.GO_VERSION }}
          cache: false

      - name: Pre-Start Setup
        run: |
          git config --global url."https://${{ secrets.PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global http.sslVerify false
          rm -rf configs/.env

      - name: Get Dependencies
        run: |
          go mod download

      - name: Start Server
        run: |
          go run main.go &

      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Install Newman
        run: |
          npm install -g newman

      - name: Wait for Server to Start
        run: |
          chmod +x ./wait-for-it.sh
          ./wait-for-it.sh 127.0.0.1:8000 --timeout=300 --strict -- echo "Server is up"

      - name: Create Trigger
        run: |
          echo "Waiting for MySQL to become available..."
          while ! mysqladmin ping -h127.0.0.1 -P3306 -uroot -proot --silent; do
            sleep 1
          done
          mysql -h 127.0.0.1 -P3306 -u root -proot zs_cloud_api < .github/setups/create_triggers.sql

      - name: Run Postman Tests
        run: |
          newman run postman-collection/zs-cloud-api-tests.postman_collection.json -e postman-collection/zs-cloud-api-test.postman_environment.json