name: Build and Deploy

on:
  pull_request:
    types: [review_requested]
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  build:
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/main')
    uses: zopsmart/app-template/.github/workflows/ui_build.yaml@ui-reusable
    secrets:
      PAT: ${{secrets.PAT}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  stage_deployment:
    needs: [ build ]
    if: (github.ref == 'refs/heads/main')
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_FILE_PATH: "Dockerfile"
            app_name: "hiring-motion-ui"
            namespace: "hiringmotion-stage"
            type: "deployment"

    uses: zopsmart/app-template/.github/workflows/ui_stage_deploy.yaml@ui-reusable

    with:
      ARTIFACT_PATH: ${{ matrix.artifact_path }}
      DOCKER_FILE_PATH: ${{ matrix.DOCKER_FILE_PATH }}
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      registry: gcr.io
      username: _json_key
      GCR_PROJECT: zs-products
      CLUSTER_NAME: products-cluster
      CLUSTER_PROJECT: zs-products
      SHA: ${{ github.sha }}
      TYPE: ${{ matrix.type }}


    secrets:
      GCR_KEY: ${{ secrets.GCR_JSON_KEY }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      PAT: ${{ secrets.PAT }}

  prod_deployment:
    needs: [ stage_deployment ]
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_FILE_PATH: "Dockerfile"
            app_name: "hiring-motion-ui"
            namespace: "hiringmotion"
            type: "deployment"

    uses: zopsmart/app-template/.github/workflows/gcr_prod_deploy.yaml@main
    with:
      registry: gcr.io
      username: _json_key
      GCR_PROJECT: zs-products
      APP_NAME: ${{ matrix.app_name }}
      CLUSTER_NAME: products-cluster
      NAMESPACE: ${{ matrix.namespace }}
      CLUSTER_PROJECT: zs-products
      TYPE: ${{ matrix.type }}

    secrets:
      GCR_KEY: ${{ secrets.GCR_JSON_KEY }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      PAT: ${{ secrets.PAT }}
