name: Go - Lint, Test & Build

on:
  pull_request:
    types: [review_requested]
    branches:
      - main
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  test:
    uses: zopsmart/app-template/.github/workflows/go_build.yaml@main
    with:
      POSTMAN_ENABLED: false
      TESTCOVERAGE_THRESHOLD: 10
      APP_NAME: "."
    name: Test and Build
    secrets:
      PAT: ${{ secrets.STAGE_PAT }}


  stage_deployment:
    needs: [ test ]
    if: (github.ref == 'refs/heads/main') && (github.event_name == 'push')
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_commands: "<build command>"
            artifact_path: "based on build"
            DOCKER_FILE_PATH: "."
            app_name: ${{ vars.STAGE_APP_NAME }}
            namespace: ${{ vars.STAGE_NAMESPACE }}
    uses: zopsmart/app-template/.github/workflows/go_gar_stage_deploy.yaml@main
    with:
      BUILD_COMMAND: ${{ matrix.build_commands }}
      ARTIFACT_PATH: ${{ matrix.artifact_path }}
      DOCKER_FILE_PATH: ${{ matrix.DOCKER_FILE_PATH }}
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.STAGE_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.STAGE_GAR_REGISTRY }}
      CLUSTER_PROJECT: ${{ vars.STAGE_CLUSTER_PROJECT }}
      CLUSTER_NAME: ${{ vars.STAGE_CLUSTER_NAME }}
      HELM_VALUES_PATH: ./helm-values/stage.yaml
      SHA: ${{ needs.test.outputs.SHA }}
    secrets:
      PAT: ${{ secrets.STAGE_PAT }}
      GAR_KEY: ${{ secrets.STAGE_DEPLOY_KEY }}

  containerize_and_push_prod:
    name: Server-Prod
    if: ${{ startsWith(github.ref, 'refs/tags/v')}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: ${{ vars.STAGE_APP_NAME }}
            namespace: ${{ vars.STAGE_NAMESPACE }}
    uses: zopsmart/app-template/.github/workflows/go_gar_prod_deploy.yaml@main
    with:
      APP_NAME: ${{ matrix.app_name }}
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.PROD_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.PROD_GAR_REGISTRY }}
      CLUSTER_PROJECT: ${{ vars.PROD_CLUSTER_PROJECT }}
      CLUSTER_NAME: ${{ vars.PROD_CLUSTER_NAME }}
      NAMESPACE: ${{ matrix.namespace }}
      HELM_VALUES_PATH: ./helm-values/prod.yaml
    secrets:
      PAT: ${{ secrets.PROD_PAT }}
      GAR_KEY: ${{ secrets.PROD_DEPLOY_KEY }}

