name: Build and Deploy

on:
  pull_request:
    types: [review_requested]
  push:
    tags:
      - '*'
    branches:
      - main
env:

  APP_NAME: app-name


jobs:
  test:
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/main')
    uses: zopsmart/zs-workflows/.github/workflows/go_build.yaml@main
    with:
      TESTCOVERAGE_THRESHOLD: 90
      APP_NAME: "postman collection should have file structure - postman-collections/<APP_NAME>.postman-collection.json"
      POSTMAN_ENABLED: false
      ADD_SCHEMA: "true or false, to add schema to db"
      SCHEMA_COMMAND:  "command to load schema to database,
                      mysql - host = 127.0.0.1, user = root , password = password, database test
                      postgres - host = 127.0.0.1, user = postgres, password = password, database test"
      EXTRA_DEPENDENCIES: "ture or false , to load extra dependencies"
      DEPENDENCIES_COMMAND: |
        "commands to install dependencies"
        ""
      MYSQL_ENABLE: "to enable MYSQL service"
      POSTGRES_ENABLE: "to enable POSTGRES service"
      REDIS_ENABLE: "to enable REDIS service"
      ZIPKIN_ENABLE: "to enable ZIPKIN service"
      ELASTIC_SEARCH_ENABLE: "to enable ELASTIC_SEARCH service"
      KAFKA_ENABLE: "to enable KAFKA service"
      MONGO_ENABLE: "to enable MONGO service"
      MSSQL_ENABLE: "to enable MSSQL service"
      DYNAMODB_ENABLE: "to enable DYNAMODB service"
      CASSANDRA_ENABLE: "to enable CASSANDRA service"
    secrets:
      PAT: ${{secrets.PAT}}

  stage_deployment:
    needs: [ test ]
    if: (github.ref == 'refs/heads/main')
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_commands: "<build command>"
            artifact_path: "based on build command"
            DOCKER_FILE_PATH: "." # add step to grant executable permission to binary in docker file ex. chmod 777 /main
            app_name: "app-name"
            namespace: "namespace-name"
            type: "deployment or cron"
            deploy: "true or false, default is true" #whether you want to deploy the service
          - build_commands: "<build command>"
            artifact_path: "based on build command"
            DOCKER_FILE_PATH: "./cron/" # add step to grant executable permission to binary in docker file ex. chmod 777 /main
            app_name: "cron-name"
            namespace: "namespace-name"
            type: "cron"
            deploy: "true or false, default is true" #whether you want to deploy the service
          - build_commands: "<build command>"
            artifact_path: "based on build command"
            DOCKER_FILE_PATH: "./script/" # add step to grant executable permission to binary in docker file ex. chmod 777 /main
            app_name: "script-name"
            namespace: "namespace-name"
            deploy: "true or false, default is true" #whether you want to deploy the service
    uses: zopsmart/zs-workflows/.github/workflows/go_gcr_stage_deploy.yaml@main

    with:
      EXTRA_DEPENDENCIES: "ture or false , to load extra dependencies"
      DEPENDENCIES_COMMAND: |
        "commands to install dependencies"
        ""
      BUILD_COMMAND: ${{ matrix.build_commands }}
      ARTIFACT_PATH: ${{ matrix.artifact_path }}
      DOCKER_FILE_PATH: ${{ matrix.DOCKER_FILE_PATH }}
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      registry: gcr.io
      username: _json_key
      GCR_PROJECT: zs-products
      CLUSTER_NAME: products-cluster
      CLUSTER_PROJECT: zs-products
      SHA: ${{ needs.test.outputs.SHA }}
      TYPE: ${{ matrix.type }}
      DEPLOY: ${{ matrix.deploy }}


    secrets:
      GCR_KEY: ${{ secrets.GCR_JSON_KEY }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      PAT: ${{ secrets.PAT }}

  prod_deployment:
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: "app-name"
            namespace: "namespace-name"
            type: "deployment"
            deploy: "true or false, default is true" #whether you want to deploy the service
          - app_name: "cron-name"
            namespace: "namespace-name"
            type: "cron"
            deploy: "true or false, default is true" #whether you want to deploy the service
    uses: zopsmart/zs-workflows/.github/workflows/go_gcr_prod_deploy.yaml@main
    with:
      registry: gcr.io
      username: _json_key
      GCR_PROJECT: zs-products
      APP_NAME: ${{ matrix.app_name }}
      CLUSTER_NAME: products-cluster
      NAMESPACE: ${{ matrix.namespace }}
      CLUSTER_PROJECT: zs-products
      TYPE: ${{ matrix.type }}
      DEPLOY: ${{ matrix.deploy }}

    secrets:
      GCR_KEY: ${{ secrets.GCR_JSON_KEY }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      PAT: ${{ secrets.PAT }}
