name: Build sample-api

on:
  push:
    branches:
      - "main"
      - "development"
      - "workflow"

env:
   GOPRIVATE: developer.zopsmart.com/go/gofr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          id: Go

      - name: Checkout code into go module directory
        uses: actions/checkout@v2

      - name: Fetch dependencies
        run: |
          git config --global url."https://${{ secrets.GHA_PAT }}:x-oauth-basic@github.com/zopsmart".insteadOf "https://github.com/zopsmart"
          git config --global http.sslVerify false
          go get -v -t -d ./...

      - name: Make Directory
        run: mkdir build

      - name: Test
        run: |
          export GOFR_ENV=test
          go test ./... -short -v -coverprofile build/coverage.txt -coverpkg=./...
          cat build/coverage.txt  > build/coverage.out
          go tool cover -func build/coverage.out

      - name: Setup linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
          golangci-lint --version

      - name: Linter Check
        run: |
          golangci-lint run --timeout 5m0s

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: main


