name: "stage deploy"
on:
  workflow_call:
    inputs:
      CLUSTER_NAME:
        description: 'required input'
        required: true
        type: string

      CLUSTER_PROJECT:
        description: 'required input'
        required: true
        type: string

      NAMESPACE:
        description: 'required input'
        required: true
        type: string

      registry:
        description: 'required input'
        required: true
        type: string

      username:
        description: 'required input'
        required: true
        type: string

      GCR_PROJECT:
        description: 'required input'
        required: true
        type: string

      APP_NAME:
        description: 'required input'
        required: true
        type: string

      docker_path:
        description: 'path of docker file'
        required: true
        type: string
      HELM_VALUES_PATH:
        type: string
        required: true




    secrets:
      PAT:
        description: 'required input'
        required: true
      gar_key:
        description: 'required input'
        required: true
        


jobs:
  dockerize:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.output-image.outputs.image }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts

      - name: change permission
        run: chmod a+x main

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.IMAGE_REGISTRY }}
          username: _json_key
          password: ${{ secrets.gcr_key }}


      - name: Build and Push Docker Image to GCR
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ${{ inputs.docker_path }}/Dockerfile
          tags: gcr.io/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ github.sha }}
      - id: output-image
        run: echo "image=`echo gcr.io/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ github.sha }}`" >> "$GITHUB_OUTPUT"

  stage_deployment:
      runs-on: ubuntu-latest
      needs: dockerize
      container:
        image: ghcr.io/zopsmart/gha-images:deployments-0.1.2
        options: --rm
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      name: 🚀 Deploy Stage
      env:
        image: ${{needs.dockerize.outputs.image}}

      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Setup Helm Chart
          run: git clone https://${{ secrets.PAT }}@github.com/zopsmart/helm.git

        - name: Setup Cloud SDK
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ inputs.CLUSTER_PROJECT }}
            service_account_key: ${{ secrets.gcr_key }}
            export_default_credentials: true

        - name: Set GCloud Project and Fetch Cluster Credentials
          run: gcloud container clusters get-credentials ${{ inputs.CLUSTER_NAME }} --region=us-central1 --project=${{ inputs.CLUSTER_PROJECT }}

        - name: Update Deployment Image
          run: helm upgrade --install --set image=${{ env.image }} ${{ inputs.APP_NAME }} ./helm/service/ -f ${{ inputs.HELM_VALUES_PATH }} -n ${{ inputs.NAMESPACE }}