name: Build and Deploy Service

on:
  pull_request:
    types: [review_requested]
    branches:
      - main
      - master
      - development
  push:
    tags:
      - '*'
    branches:
      - main
      - master
      - development

jobs:
  test:
    uses: zopsmart/zs-workflows/.github/workflows/java.yaml@v0.3.0
    secrets:
      GAR_SECRET: ${{ secrets.GAR_KEY }}
      
  dockerize_deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: "training-api"
            stage_env_file_path: "path of env file to store them in configmap of stage namespace"
            prod_env_file_path: "path of env file to store them in configmap of prod namespace"
            DOCKER_FILE_PATH: "Dockerfile" #path of dockerfile including the name of the file
            stage_namespace: ${{ vars.STAGE_NAMESPACE }}
            prod_namespace: ${{ vars.PROD_NAMESPACE }}
            type: "deployment"
            deployment_tool: "kubectl" #deployment tool to use for deploying the application either helm or kubectl

    uses: zopsmart/zs-workflows/.github/workflows/java_stage_deploy.yaml@v0.3.0
    with:
      APP_NAME: ${{ matrix.app_name }}
      DOCKER_FILE_PATH: ${{ matrix.DOCKER_FILE_PATH }}
      STAGE_ENV_FILE_PATH: ${{ matrix.stage_env_file_path }}
      PROD_ENV_FILE_PATH: ${{ matrix.prod_env_file_path }}
      STAGE_NAMESPACE: ${{ matrix.stage_namespace }}
      PROD_NAMESPACE: ${{ matrix.prod_namespace }}
      CLUSTER_NAME: ${{ vars.STAGE_CLUSTER_NAME }}
      CLUSTER_PROJECT: ${{ vars.STAGE_CLUSTER_PROJECT }}
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.STAGE_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.STAGE_GAR_REGISTRY }}
      TYPE: ${{ matrix.type }}
      DEPLOYMENT_TOOL: ${{ matrix.deployment_tool }}

    secrets:
      PAT: ${{ secrets.PAT }} 
      GAR_SECRET: ${{ secrets.GAR_KEY }}
      GAR_KEY: ${{ secrets.GAR_KEY }}

  prod_deployment:
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: "training-api"
            namespace: "training"
            env_file_path: "path of env file to store them in configmap of prod namespace"
            type: "deployment"
            deployment_tool: "kubectl" #deployment tool to use for deploying the application either helm or kubectl
    uses: zopsmart/zs-workflows/.github/workflows/prod_deploy.yaml@v0.3.0
    with:
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.PROD_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.PROD_GAR_REGISTRY }}
      CLUSTER_NAME: ${{ vars.PROD_CLUSTER_NAME }}
      CLUSTER_PROJECT: ${{ vars.PROD_CLUSTER_PROJECT }}
      ENV_FILE_PATH: ${{ matrix.env_file_path }}
      TYPE: ${{ matrix.type }}
      DEPLOYMENT_TOOL: ${{ matrix.deployment_tool }}

    secrets:
      GAR_KEY: ${{ secrets.GAR_KEY }}

