name: Build and Deploy Service

on:
  pull_request_review:
    types: [ submitted ]
    branches:
      - main
      - development
  push:
    tags:
      - '*'
    branches:
      - main
      - development

jobs:
  build:
    uses: zopsmart/zs-workflows/.github/workflows/java_build.yaml@v0.3.5
    secrets:
      GAR_SECRET: ${{ secrets.GAR_KEY }}

  stage_deployment:
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_FILE_PATH: "Dockerfile"
            app_name: "training-api"
            namespace: "training-stage"
            type: "deployment"


    with:
      IMAGE_REGISTRY: gcr.io
      username: _json_key
      PROJECT_NAME: "zs-products"
      DOCKER_FILE_PATH: ${{ matrix.DOCKER_FILE_PATH }}
      BUILD_ARGUMENTS: |
        VERSION=edge
        APP_NAME=main
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      CLUSTER_NAME: products-cluster
      CLUSTER_PROJECT: zs-products
      GCR_PROJECT: zs-products
      SHA: ${{ github.sha }}
      TYPE: ${{ matrix.type }}
      ARTIFACT_PATH: build/libs
      ARTIFACT_NAME: artifacts
      ENV_FILE_PATH: ./configs/.stage.env
    secrets:
      GCR_KEY: ${{ secrets.GCR_KEY }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY}}

    uses: zopsmart/zs-workflows/.github/workflows/gcr_stage_deploy.yaml@v0.3.5

  prod_deployment:
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: "training-api"
            namespace: "training"
            type: "deployment"


    with:
      IMAGE_REGISTRY: gcr.io
      username: _json_key
      PROJECT_NAME: "zs-products"
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      CLUSTER_NAME: products-cluster
      CLUSTER_PROJECT: zs-products
      GCR_PROJECT: zs-products
      TYPE: ${{ matrix.type }}
      ARTIFACT_PATH: build/libs
      ARTIFACT_NAME: artifacts
      ENV_FILE_PATH: ./configs/.prod.env
    secrets:
      GCR_KEY: ${{ secrets.GCR_KEY }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY}}

    uses: zopsmart/zs-workflows/.github/workflows/gcr_prod_deploy.yaml@v0.3.5
