name: '<app_name>'
project_name: '<project_name>'
cluster_name: '<cluster_name>'
DB_NAME: '<db_name>'  # if service do not require a DB, field can be ignored
DB_DIALECT: '<db_dialect>' # if service do not require a DB, field can be ignored
DB_USER: '<db_user>' # if service do not require a DB, field can be ignored

minMemory: "512Mi"
maxMemory: "1Gi"
maxCPU: "1.5"

env:
  cloud: "GCP"
  TRACER_URL: "https://tempo.observability-dev.gcpgap.zopsmart.com"  # url values changes depending on the environment
  TRACER_EXPORTER: "zipkin"

alerts:
  # alerts will be enabled with the threshold values provided below
  standard:
    infra:
      unavailable_replicas_threshold: 0                   # Alert if the available replicas is lesser than number of desired replicas
      pod_restart_threshold: 0                            # Alert if the pod restarts goes beyond threshold over a 5-minute window.
      pod_restart_time_window: "5m"                       # Time window  ,default "5m"
      hpa_nearing_max_pod_threshold: 80                   # Alert if replica count crosses the threshold percentage of max pod count
      service_memory_utilization_threshold: 90            # Alert if service memory exceeds threshold
      service_cpu_utilization_threshold: 90               # Alert if service cpu exceeds threshold
      service_cpu_utilization_time_window: "5m"           # Time window for service cpu utilization
      health_check_failure_threshold: 50                  # Alert if  application health-check failures goes beyond 50 in a 5-minute window.
      health_check_failure_time_window: "5m"              # Time window  ,default "5m"
    response_code:
      400:
        absolute_threshold: 500                           # Alert if the 400 response code errors in application goes beyond 500 in a given time window.
        absolute_time_window: "5m"                        # Time window for bad_request_threshold ,default "5m"
        percentage_threshold: 70                          # Alert if the 400 response code errors in application goes beyond 70 percent in a given time window.
        percentage_time_window: "5m"                      # Time window for bad_request_percentage_threshold ,default "5m"
        adaptive_threshold: 15                            # Alert if the 400 response code in  an application goes beyond 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Reference Time window  ,default "24h"
        adaptive_reference_time_window: "3h"             # Time window  ,default "3h"
      401:
        absolute_threshold: 100                           # Alert if the 401 response code errors in application goes beyond 100 in a 5-minute window.
        absolute_time_window: "5m"                        # Time window  ,default "5m"
        percentage_threshold: 20                          # Alert if the 401 response code errors in application goes beyond 20 percent in a 5-minute window.
        percentage_time_window: "5m"                      # Time window  ,default "5m"
        adaptive_threshold: 15                            # Alert if the  401 response code count in  an application goes beyond 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Time window  ,default "5m"
        adaptive_reference_time_window: "3h"             # Reference Time window  ,default "3h"
      403:
        absolute_threshold: 100                           # Alert if the 403 response code errors in application goes beyond 100 in a 5-minute window.
        absolute_time_window: "5m"                        # Time window  ,default "5m"
        percentage_threshold: 70                          # Alert if the 403 response code errors in application goes beyond 70 percent in a 5-minute window.
        percentage_time_window: "5m"                      # Time window  ,default "5m"
        adaptive_threshold: 15                            # Alert if the  403 response code count in  an application goes beyond 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Time window  ,default "5m"
        adaptive_reference_time_window: "3h"             # Reference Time window  ,default "3h"
      404:
        absolute_threshold: 500                           # Alert if the 404 response code errors in application goes beyond 500 in a 5-minute window.
        absolute_time_window: "5m"                        # Time window  ,default "5m"
        percentage_threshold: 20                          # Alert if the 404 response code errors in application goes beyond 20 percent in a 5-minute window.
        percentage_time_window: "5m"                      # Time window  ,default "5m"
        adaptive_threshold: 15                            # Alert if the 404 response code in  an application goes beyond 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Time window  ,default "5m"
        adaptive_reference_time_window: "3h"             # Reference Time window  ,default "3h"
      5xx:
        absolute_threshold: 40                            # Alert if the 5XX response code errors in application goes beyond 40 in a 5-minute window.
        absolute_time_window: "5m"                        # Time window  ,default "5m"
        percentage_threshold: 40                          # Alert if the 5XX response code errors in application goes beyond 40 percent in a given time window.
        percentage_time_window: "5m"                      # Time window  ,default "5m"
        adaptive_threshold: 15                            # Alert if the 500 response code count in  an application goes beyond 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Time window  ,default "5m"
        adaptive_reference_time_window: "3h"             # Reference Time window  ,default "3h"
        severity_level: "critical"                        # Severity level of alert
      424:
        absolute_threshold: 10                            # Alert if the 424 response code errors in application goes beyond 10 in a 5-minute window.
        absolute_time_window: "5m"                        # Time window  ,default "5m"
        percentage_threshold: 10                          # Alert if the 424 response code errors in application goes beyond 10 percent in a 5-minute window.
        percentage_time_window: "5m"                      # Time window  ,default "5m"
        adaptive_threshold: -1                            # Alert if the 424 response code in  an application goes beyond 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Time window  ,default "5m"
        adaptive_reference_time_window: "3h"             # Reference Time window  ,default "3h"
      409:
        absolute_threshold: 100                           # Alert if the 409 response code errors in application goes beyond 100 in a 5-minute window.
        absolute_time_window: "5m"                        # Time window  ,default "5m"
        percentage_threshold: 20                          # Alert if the 409 response code errors in application goes beyond 20 percent in a 5-minute window.
        percentage_time_window: "5m"                      # Time window  ,default "5m"
        adaptive_threshold: -1                            # Alert if the 409 response code in  an application goes beyond 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Time window  ,default "5m"
        adaptive_reference_time_window: "3h"             # Reference Time window  ,default "3h"
      201:
        absolute_threshold: -1                            # Alert if the 201 response code errors in application goes below 10 in a 5-minute window.
        absolute_time_window: "5m"                        # Time window  ,default "5m"
        percentage_threshold: -1                          # Alert if the 201 response code errors in application goes below 20 percent in a 5-minute window.
        percentage_time_window: "5m"                      # Time window  ,default "5m"
        adaptive_threshold: -1                            # Alert if the 201 response code in  an application goes below 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Time window  ,default "5m"
        adaptive_reference_time_window: "3h"             # Reference Time window  ,default "3h"
    outbound_response_code:
      400:
        absolute_threshold: 500                           # Alert if the outbound 400 response code errors in application goes beyond 500 in a given time window.
        absolute_time_window: "5m"                        # Time window for bad_request_threshold ,default "5m"
        percentage_threshold: 70                          # Alert if the outbound 400 response code errors in application goes beyond 70 percent in a given time window.
        percentage_time_window: "5m"                      # Time window for bad_request_percentage_threshold ,default "5m"
        adaptive_threshold: 15                            # Alert if the outbound 400 response code in  an application goes beyond 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Reference Time window  ,default "24h"
        adaptive_reference_time_window: "3h"             # Time window  ,default "3h"
      401:
        absolute_threshold: 100                           # Alert if the outbound 401 response code errors in application goes beyond 100 in a 5-minute window.
        absolute_time_window: "5m"                        # Time window  ,default "5m"
        percentage_threshold: 20                          # Alert if the outbound 401 response code errors in application goes beyond 20 percent in a 5-minute window.
        percentage_time_window: "5m"                      # Time window  ,default "5m"
        adaptive_threshold: 15                            # Alert if the outbound 401 response code count in  an application goes beyond 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Time window  ,default "5m"
        adaptive_reference_time_window: "3h"             # Reference Time window  ,default "3h"
      403:
        absolute_threshold: 100                           # Alert if the outbound 403 response code errors in application goes beyond 100 in a 5-minute window.
        absolute_time_window: "5m"                        # Time window  ,default "5m"
        percentage_threshold: 70                          # Alert if the outbound 403 response code errors in application goes beyond 70 percent in a 5-minute window.
        percentage_time_window: "5m"                      # Time window  ,default "5m"
        adaptive_threshold: 15                            # Alert if the outbound 403 response code count in  an application goes beyond 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Time window  ,default "5m"
        adaptive_reference_time_window: "3h"             # Reference Time window  ,default "3h"
      404:
        absolute_threshold: 500                           # Alert if the outbound 404 response code errors in application goes beyond 500 in a 5-minute window.
        absolute_time_window: "5m"                        # Time window  ,default "5m"
        percentage_threshold: 20                          # Alert if the outbound 404 response code errors in application goes beyond 20 percent in a 5-minute window.
        percentage_time_window: "5m"                      # Time window  ,default "5m"
        adaptive_threshold: 15                            # Alert if the outbound 404 response code in  an application goes beyond 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Time window  ,default "5m"
        adaptive_reference_time_window: "3h"             # Reference Time window  ,default "3h"
      5xx:
        absolute_threshold: 40                            # Alert if the outbound 5XX response code errors in application goes beyond 40 in a 5-minute window.
        absolute_time_window: "5m"                        # Time window  ,default "5m"
        percentage_threshold: 40                          # Alert if the outbound 5XX response code errors in application goes beyond 40 percent in a given time window.
        percentage_time_window: "5m"                      # Time window  ,default "5m"
        adaptive_threshold: 15                            # Alert if the outbound  500 response code count in  an application goes beyond 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Time window  ,default "5m"
        adaptive_reference_time_window: "3h"             # Reference Time window  ,default "3h"
        severity_level: "critical"                        # Severity level of alert
      201:
        absolute_threshold: -1                            # Alert if the outbound 201 response code errors in application goes below 10 in a 5-minute window.
        absolute_time_window: "5m"                        # Time window  ,default "5m"
        percentage_threshold: -1                          # Alert if the outbound 201 response code errors in application goes below 20 percent in a 5-minute window.
        percentage_time_window: "5m"                      # Time window  ,default "5m"
        adaptive_threshold: -1                            # Alert if the outbound 201 response code in  an application goes below 15 percent in a 5min window over last 24-hour window.
        adaptive_time_window: "5m"                        # Time window  ,default "5m"
        adaptive_reference_time_window: "3h"             # Time window  ,default "3h"
    request_count:
      adaptive_threshold: 30                              # Alert if the number of requests in the last 5 mins is higher/lower than 30% than the average for last 24 hours.
      adaptive_time_window: "5m"                          # Time window  ,default "5m"
      adaptive_reference_time_window: "3h"                # Time window  ,default "3h"
    outbound_request_count:
      adaptive_threshold: 30                              # Alert if the number of outbound requests in the last 5 mins is higher/lower than 30% than the average for last 24 hours
      adaptive_time_window: "5m"                          # Time window  ,default "5m"
      adaptive_reference_time_window: "3h"                # Time window  ,default "3h"
    response_time:
      absolute_warning_threshold: 0.250                   # Alert if 95 percentile application response time increases beyond 250ms over a 5-minute window.
      absolute_warning_time_window: "5m"                  # Time window  ,default "5m"
      absolute_critical_threshold: 0.75                   # Alert if 95 percentile application response time increases beyond 750ms over a 5-minute window
      absolute_critical_time_window: "5m"                 # Time window  ,default "5m"
      adaptive_threshold: 15                              # Alert if 99 percentile application response time increases beyond 15 percent in a last 5-minute window over last 24-hour window
      adaptive_percentile: 0.99                           # The configurable application response percentile
      adaptive_time_window: "5m"                          # Time window  ,default "5m"
      adaptive_reference_time_window: "3h"               # Time window total  ,default "3h"
    outbound_response_time:
      absolute_warning_threshold: -1                      # Alert if 95 percentile application outbound response time increases beyond -1000ms over a 5-minute window.
      absolute_warning_time_window: "5m"                  # Time window  ,default "5m"
      absolute_critical_threshold: -1                     # Alert if 95 percentile application outbound response time increases beyond -1000ms over a 5-minute window
      absolute_critical_time_window: "5m"                 # Time window  ,default "5m"
      adaptive_threshold: -1                              # Alert if 99 percentile application outbound response time increases beyond -1 percent in a last 5-minute window over last 24-hour window
      adaptive_percentile: 0.99                           # The configurable application outbound response percentile
      adaptive_time_window: "5m"                          # Time window  ,default "5m"
      adaptive_reference_time_window: "3h"               # Time window total  ,default "3h"



