name: Build and Deploy Service

on:
  pull_request:
    types: [review_requested]
    branches:
      - main
      - master
      - development
  push:
    tags:
      - '*'
    branches:
      - main
      - master
      - development

jobs:
  build:
    uses: zopsmart/zs-workflows/.github/workflows/java_build.yaml@main
    secrets:
      GH_PASSWORD: ${{ secrets.GH_PACKAGE_PASS }}
      GH_USERNAME: ${{ secrets.GH_PACKAGE_USER }}

  update_configmap:
    uses: zopsmart/zs-workflows/.github/workflows/update-configmap.yaml@main
    with:
      APP_NAME: "app-name"
      ENV_FILE_NAME: "path of env file"
      CLUSTER_PROJECT: "cluster-project"
      CLUSTER_NAME: "cluster-name"
      NAMESPACE: "namespace"
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

  stage_deployment:
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_FILE_PATH: "Dockerfile"
            app_name: "training-api"
            namespace: "training-stage"
            type: "deployment"


    with:
      IMAGE_REGISTRY: gcr.io
      username: _json_key
      PROJECT_NAME: "zs-products"
      DOCKER_FILE_PATH: ${{ matrix.DOCKER_FILE_PATH }}
      BUILD_ARGUMENTS: |
        VERSION=edge
        APP_NAME=main
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      CLUSTER_NAME: products-cluster
      CLUSTER_PROJECT: zs-products
      GCR_PROJECT: zs-products
      SHA: ${{ github.sha }}
      TYPE: ${{ matrix.type }}
      ARTIFACT_PATH: build/libs
      ARTIFACT_NAME: artifacts
    secrets:
      GCR_KEY: ${{ secrets.GCR_KEY }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY}}

    uses: zopsmart/zs-workflows/.github/workflows/gcr_stage_deploy.yaml@main

  prod_deployment:
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: "training-api"
            namespace: "training"
            type: "deployment"


    with:
      IMAGE_REGISTRY: gcr.io
      username: _json_key
      PROJECT_NAME: "zs-products"
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      CLUSTER_NAME: products-cluster
      CLUSTER_PROJECT: zs-products
      GCR_PROJECT: zs-products
      TYPE: ${{ matrix.type }}
      ARTIFACT_PATH: build/libs
      ARTIFACT_NAME: artifacts
    secrets:
      GCR_KEY: ${{ secrets.GCR_KEY }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY}}

    uses: zopsmart/zs-workflows/.github/workflows/gcr_prod_deploy.yaml@main
