name: Build and Deploy

on:
  pull_request:
    types:
      - review_requested
    branches:
      - main
      - master
      - development
  push:
    tags:
      - '*'
    branches:
      - main
      - master
      - development

jobs:
  build:
    uses: zopsmart/zs-workflows/.github/workflows/ui_npm.yaml@main
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: ${{ vars.STAGE_APP_NAME }}
            stage_namespace: ${{ vars.STAGE_NAMESPACE }}
            prod_namespace: ${{ vars.PROD_NAMESPACE }}
            build_commands: "<build command>"
            DOCKER_FILE_PATH: "." # add step to grant executable permission to binary in docker file ex. chmod 777 /main
    with:
      APP_NAME: ${{ matrix.app_name }}
      NODE_VERSION: '18.x'
      BUILD_COMMAND: |
        commands to build
      TEST_COMMAND: |
        CI=false npm run test:coverage
      LINTER_CHECKS: true
      PRETTIER_CHECKS: true
      ENABLE_TESTS: false
      DEPENDENCIES_FLAG: --legacy-peer-deps //not required
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.STAGE_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.STAGE_GAR_REGISTRY }}
      CLUSTER_PROJECT: ${{ vars.STAGE_CLUSTER_PROJECT }}
      CLUSTER_NAME: ${{ vars.STAGE_CLUSTER_NAME }}
      STAGE_NAMESPACE: ${{ matrix.stage_namespace }}
      PROD_NAMESPACE: ${{ matrix.prod_namespace }}
      STAGE_ENV_FILE_PATH: ./configs/.stage.env
      PROD_ENV_FILE_PATH: ./configs/.prod.env
      DOCKER_FILE_PATH: ${{ matrix.DOCKER_FILE_PATH }}
      REACT_APP:  # true if its react service, default is false skip this if not a react service
    secrets:
      PAT: '${{ secrets.PAT }}'
      NPM_TOKEN: '${{ secrets.PRIVATE_GITHUB_PACKAGE_PAT }}' //not required
  stage_deployment:
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: ${{ vars.STAGE_APP_NAME }}
            namespace: ${{ vars.STAGE_NAMESPACE }}
            type: "deployment"
            deployment_tool: "helm" #deployment tool to use for deploying the application either helm or kubectl

    uses: zopsmart/zs-workflows/.github/workflows/stage_deploy.yaml@main
    with:
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.STAGE_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.STAGE_GAR_REGISTRY }}
      CLUSTER_NAME: ${{ vars.STAGE_CLUSTER_NAME }}
      CLUSTER_PROJECT: ${{ vars.STAGE_CLUSTER_PROJECT }}
      HELM_VALUES_PATH: './helm-values/stage.yaml'
      IMAGE: ${{ needs.build.outputs.image }}
      TYPE: ${{ matrix.type }}
      DEPLOYMENT_TOOL: ${{ matrix.deployment_tool }}
    secrets:
      GAR_KEY: '${{ secrets.STAGE_DEPLOY_KEY }}'
      PAT: '${{ secrets.STAGE_PAT }}'
  prod_deployment:
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: ${{ vars.STAGE_APP_NAME }}
            namespace: ${{ vars.STAGE_NAMESPACE }}
            type: "deployment"
            deployment_tool: "helm" #deployment tool to use for deploying the application either helm or kubectl
    uses: zopsmart/zs-workflows/.github/workflows/prod_deploy.yaml@main
    with:
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.PROD_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.PROD_GAR_REGISTRY }}
      CLUSTER_NAME: ${{ vars.PROD_CLUSTER_NAME }}
      CLUSTER_PROJECT: ${{ vars.PROD_CLUSTER_PROJECT }}
      HELM_VALUES_PATH: ./helm-values/prod.yaml
      IMAGE: ${{ needs.test.outputs.image }}
      TYPE: ${{ matrix.type }}
      DEPLOYMENT_TOOL: ${{ matrix.deployment_tool }}
    secrets:
      GAR_KEY: '${{ secrets.STAGE_DEPLOY_KEY }}'
      PAT: '${{ secrets.PROD_PAT }}'
