name: Build and Deploy

on:
  pull_request_review:
    types: [ submitted ]
    branches:
      - main
      - development
  push:
    tags:
      - '*'
    branches:
      - main
      - development

jobs:
  test:
    uses: zopsmart/zs-workflows/.github/workflows/ui_npm.yaml@v0.3.9
    with:
      APP_NAME: ${{ matrix.app_name }}
      NODE_VERSION: '18.x'
      TEST_COMMAND: |
        CI=false npm run test:coverage
      LINTER_CHECKS: true
      PRETTIER_CHECKS: true
      ENABLE_TESTS: false
      DEPENDENCIES_FLAG: --legacy-peer-deps //not required
    secrets:
      PAT: ${{ secrets.PAT }}

  dockerize_deploy:
    needs: [ test ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: ${{ vars.STAGE_APP_NAME }}
            build_commands: "<build command>"
            DOCKER_FILE_PATH: "Dockerfile" #path of dockerfile including the name of the file
            stage_namespace: ${{ vars.STAGE_NAMESPACE }}
            prod_namespace: ${{ vars.PROD_NAMESPACE }}
            type: "deployment"
            stage_env_file_path: "path of env file to store them in configmap of stage namespace"
            prod_env_file_path: "path of env file to store them in configmap of prod namespace"

    uses: zopsmart/zs-workflows/.github/workflows/npm_stage_deploy.yaml@v0.3.9
    with:
      APP_NAME: ${{ matrix.app_name }}
      NODE_VERSION: '18.x'
      BUILD_COMMAND: ${{ matrix.build_commands }}
      DOCKER_FILE_PATH: ${{ matrix.DOCKER_FILE_PATH }}
      STAGE_ENV_FILE_PATH: ${{ matrix.stage_env_file_path }}
      PROD_ENV_FILE_PATH: ${{ matrix.prod_env_file_path }}
      STAGE_NAMESPACE: ${{ matrix.stage_namespace }}
      PROD_NAMESPACE: ${{ matrix.prod_namespace }}
      CLUSTER_NAME: ${{ vars.STAGE_CLUSTER_NAME }} // Skip this input, if only dockerize is needed
      CLUSTER_PROJECT: ${{ vars.STAGE_CLUSTER_PROJECT }}
      CLUSTER_REGION: cluster region
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.STAGE_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.STAGE_GAR_REGISTRY }}
      TYPE: ${{ matrix.type }}
      SHA: ${{ needs.test.outputs.SHA }}
      REACT_APP:  # true if its react service, default is false skip this if not a react service
    secrets:
      PAT: ${{ secrets.STAGE_PAT }}
      NPM_TOKEN: ${{ secrets.PRIVATE_GITHUB_PACKAGE_PAT }} #not required
      GAR_KEY: ${{ secrets.STAGE_GAR_KEY }}

  prod_deployment:
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: ${{ vars.STAGE_APP_NAME }}
            namespace: ${{ vars.PROD_NAMESPACE }}
            env_file_path: "path of env file to store them in configmap of prod namespace"
            type: "deployment"
    uses: zopsmart/zs-workflows/.github/workflows/prod_deploy.yaml@v0.3.9
    with:
      APP_NAME: ${{ matrix.app_name }}
      NAMESPACE: ${{ matrix.namespace }}
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.PROD_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.PROD_GAR_REGISTRY }}
      CLUSTER_NAME: ${{ vars.PROD_CLUSTER_NAME }}
      CLUSTER_PROJECT: ${{ vars.PROD_CLUSTER_PROJECT }}
      CLUSTER_REGION: cluster region
      ENV_FILE_PATH: ${{ matrix.env_file_path }}
      TYPE: ${{ matrix.type }}
      REACT_APP:  # true if its react service, default is false skip this if not a react service

    secrets:
      GAR_KEY: ${{ secrets.STAGE_GAR_KEY }}
