name: Build and Deploy
'on':
  pull_request_review:
    types: [ submitted ]
  push:
    tags:
      - '*'
    branches:
      - main
      - development

jobs:
  build:
    uses: zopsmart/zs-workflows/.github/workflows/ui_yarn_build.yaml@v0.3.5
    with:
      APP_NAME: rlog-api
      NODE_VERSION: '18.x'
      BUILD_COMMAND: |
        yarn build
        tar -zcf rlog-api.zip dist
      ARTIFACT_PATH: |
        rlog-api.zip
        node_modules.zip
      ENABLE_TESTS: false
    secrets:
      PAT: '${{ secrets.PAT }}'
      NPM_TOKEN: '${{ secrets.PRIVATE_GITHUB_PACKAGE_PAT }}'
  stage_deployment:
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_FILE_PATH: .
            app_name: ${{ vars.STAGE_APP_NAME }}
            namespace: ${{ vars.STAGE_NAMESPACE }}
    uses: zopsmart/zs-workflows/.github/workflows/ui_gar_stage_deploy.yaml@v0.3.5
    with:
      DOCKER_FILE_PATH: '${{ matrix.DOCKER_FILE_PATH }}'
      APP_NAME: '${{ matrix.app_name }}'
      NAMESPACE: '${{ matrix.namespace }}'
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.STAGE_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.STAGE_GAR_REGISTRY }}
      CLUSTER_PROJECT: ${{ vars.STAGE_CLUSTER_PROJECT }}
      CLUSTER_NAME: ${{ vars.STAGE_CLUSTER_NAME }}
      HELM_VALUES_PATH: ./helm-values/stage-values.yaml
      SHA: '${{ needs.build.outputs.SHA }}'
      CREATE_NPMRC: 'whether to create .npmrc file to get dependencies, default value is true'
      ENV_FILE_PATH: ./configs/.stage.env
      UNZIP_COMMAND: |
        tar -xf rlog-api.zip
        tar -xf node_modules.zip
    secrets:
      PAT: ${{ secrets.STAGE_PAT }}
      GAR_KEY: ${{ secrets.STAGE_DEPLOY_KEY }}
      NPM_TOKEN: ${{ secrets.PRIVATE_GITHUB_PACKAGE_PAT }}
  prod_deployment:
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: ${{ vars.PROD_APP_NAME }}
            namespace: ${{ vars.PROD_NAMESPACE }}
    uses: zopsmart/zs-workflows/.github/workflows/go_gar_prod_deploy.yaml@v0.3.5
    with:
      APP_NAME: '${{ matrix.app_name }}'
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.PROD_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.PROD_GAR_REGISTRY }}
      CLUSTER_NAME: ${{ vars.PROD_CLUSTER_NAME }}
      CLUSTER_PROJECT: ${{ vars.PROD_CLUSTER_PROJECT }}
      NAMESPACE: '${{ matrix.namespace }}'
      HELM_VALUES_PATH: ./helm-values/prod-values.yaml
      ENV_FILE_PATH: ./configs/.prod.env
    secrets:
      PAT: ${{ secrets.PROD_PAT }}
      GAR_KEY: ${{ secrets.PROD_DEPLOY_KEY }}