name: Go - Test, Build, Dockerize and Deploy

on:
  pull_request_review:
    types: [ submitted ]
    branches:
      - main
      - development
  push:
    tags:
      - '*'
    branches:
      - main
      - development

jobs:
  test:
    uses: zopsmart/zs-workflows/.github/workflows/go.yaml@v0.3.7
    with:
      POSTMAN_ENABLED: false
      GO_VERSION: 'specify go version like 1.19,1.20. Default is 1.20'
      LINTER_VERSION: default one is v1.54.2 // not required
      LINTER_TIMEOUT: default is 8m // not a required input
      TESTCOVERAGE_THRESHOLD: 10
      MODULES: |
        module1
        module2   // Give the list of modules(with their own go mod files) whose test coverage you want to include in the coverage badge
      APP_NAME: ${{ vars.STAGE_APP_NAME }} #postman collection should have file structure - postman-collections/<APP_NAME>.postman-collection.json
      ADD_SCHEMA: "true or false, if true must provide schema command"
      SCHEMA_COMMAND: "command to load schema to database,
                      mysql - host = 127.0.0.1, user = root , password = password, database test
                      postgres - host = 127.0.0.1, user = postgres, password = password, database test"
      EXTRA_DEPENDENCIES: "ture or false , to load extra dependencies"
      DEPENDENCIES_COMMAND: |
        "commands to install dependencies"
        ""
      SERVER_COMMAND: |
        "commands to execute before running server for postman"
      MYSQL_ENABLE: "to enable MYSQL service"
      POSTGRES_ENABLE: "to enable POSTGRES service"
      REDIS_ENABLE: "to enable REDIS service"
      ZIPKIN_ENABLE: "to enable ZIPKIN service"
      ELASTIC_SEARCH_ENABLE: "to enable ELASTIC_SEARCH service"
      KAFKA_ENABLE: "to enable KAFKA service"
      MONGO_ENABLE: "to enable MONGO service"
      MSSQL_ENABLE: "to enable MSSQL service"
      DYNAMODB_ENABLE: "to enable DYNAMODB service"
      CASSANDRA_ENABLE: "to enable CASSANDRA service"
    secrets:
      PAT: ${{ secrets.PAT }} #not a mandatory field, use PAT if there are any private dependencies

  dockerize_deploy:
    needs: [ test ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: ${{ vars.STAGE_APP_NAME }}
            artifact_path: "based on build command" // use same binary name used in build command
            build_commands: "<build command>"
            DOCKER_FILE_PATH: "." # add step to grant executable permission to binary in docker file ex. chmod 777 /main
            stage_namespace: ${{ vars.STAGE_NAMESPACE }}
            prod_namespace: ${{ vars.PROD_NAMESPACE }}
            type: "deployment"
            stage_env_file_path: "path of env file to store them in configmap of stage namespace"
            prod_env_file_path: "path of env file to store them in configmap of prod namespace"
    uses: zopsmart/zs-workflows/.github/workflows/go_stage_deploy.yaml@v0.3.7
    with:
      APP_NAME: ${{ matrix.app_name }}
      ARTIFACT_PATH: ${{ matrix.artifact_path }}
      EXTRA_DEPENDENCIES: "ture or false , to load extra dependencies"
      DEPENDENCIES_COMMAND: |
        "commands to install dependencies"
        ""
      GO_VERSION: 'specify go version like 1.19,1.20. Default is 1.20'
      BUILD_COMMAND: ${{ matrix.build_commands }}
      DOCKER_FILE_PATH: ${{ matrix.DOCKER_FILE_PATH }}
      STAGE_ENV_FILE_PATH: ${{ matrix.stage_env_file_path }}
      PROD_ENV_FILE_PATH: ${{ matrix.prod_env_file_path }}
      STAGE_NAMESPACE: ${{ matrix.stage_namespace }}
      PROD_NAMESPACE: ${{ matrix.prod_namespace }}
      CLUSTER_PROJECT: ${{ vars.STAGE_CLUSTER_PROJECT }}
      CLUSTER_NAME: ${{ vars.STAGE_CLUSTER_NAME }}  // Skip this input, if only dockerize is needed
      CLUSTER_REGION: cluster region
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.STAGE_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.STAGE_GAR_REGISTRY }}
      TYPE: ${{ matrix.type }}
      SHA: ${{ needs.test.outputs.SHA }}
    secrets:
      PAT: ${{ secrets.STAGE_PAT }}
      GAR_KEY: ${{ secrets.STAGE_GAR_KEY }}

  prod_deployment:
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: ${{ vars.STAGE_APP_NAME }}
            namespace: ${{ vars.PROD_NAMESPACE }}
            env_file_path: "path of env file to store them in configmap of prod namespace"
            type: "deployment"
    uses: zopsmart/zs-workflows/.github/workflows/prod_deploy.yaml@v0.3.7
    with:
      APP_NAME: ${{ matrix.app_name }}
      IMAGE_REGISTRY: us-central1-docker.pkg.dev
      GAR_PROJECT: ${{ vars.PROD_GAR_PROJECT }}
      GAR_REGISTRY: ${{ vars.PROD_GAR_REGISTRY }}
      CLUSTER_PROJECT: ${{ vars.PROD_CLUSTER_PROJECT }}
      CLUSTER_NAME: ${{ vars.PROD_CLUSTER_NAME }}
      CLUSTER_REGION: cluster region
      NAMESPACE: ${{ matrix.namespace }}
      ENV_FILE_PATH: ${{ matrix.env_file_path }}
      TYPE: ${{ matrix.type }}
    secrets:
      GAR_KEY: ${{ secrets.PROD_GAR_KEY }}
