name: "test and linters"
on:
  workflow_call:
    inputs:
      TESTCOVERAGE_THRESHOLD:
        description: 'required input'
        required: true
        type: string
      POSTMAN_ENABLED:
        required: true
        type: boolean
      APP_NAME:
        description: 'name of postman collection file'
        required: true
        type: string
      MYSQL_ENABLE:
        description: 'mysql should be installed or not'
        required: true
        type: boolean
        default: true
      POSTGRES_ENABLE:
        description: 'postgres should be installed or not'
        required: true
        type: boolean
        default: true
      REDIS_ENABLE:
        description: 'redis should be installed or not'
        required: true
        type: boolean
        default: true
    outputs:
      SHA:
        description: "commit sha for image"
        value: ${{ jobs.test.outputs.sha }}
    secrets:
      PAT:
         description: 'pat of gofr'
         required: true 
     
jobs:
  test:
    runs-on: ubuntu-latest
    name: test and linters
    container:
      image: ghcr.io/zopsmart/gha-images:go-0.1.1
      options: --rm
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}
    outputs:
      sha: ${{ steps.output-sha.outputs.sha }}
    services:
      mysql:
        image: ${{ inputs.MYSQL_ENABLE && 'mysql:8.0.31' || '' }}
        env:
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_DATABASE: "test"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      postgres:
        image: ${{ inputs.POSTGRES_ENABLE && 'postgres:15.1' || '' }}
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: test

      redis:
        image: ${{ inputs.REDIS_ENABLE && 'redis:5.0.14' || '' }}
        options: "--entrypoint redis-server"

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          git config --global url."https://${{ secrets.PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global http.sslVerify false
          go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          args: --timeout 8m

      - name: Test
        run: |
          mkdir -p temp/build
          GOFR_ENV=test go test ./... -count=1 -v -coverprofile temp/cover.out -coverpkg=./...
          cat temp/cover.out | grep -v "mock_interface" | grep -v "migrations" > temp/coverage.out

      - name: Test Coverage report
        run: |
          go tool cover -func=temp/coverage.out | tee temp/c.out

      - name: Generate and Commit Coverage Badge
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        run: |
          go install github.com/AlexBeauchemin/gobadge@latest
          gobadge -filename=temp/c.out -target=$(pwd)/README.md
          git config --global user.email "action@github.com" && git config --global user.name "GitHub-Action"
          git config --global --add safe.directory /__w/$(basename ${{ github.repository }})/$(basename ${{ github.repository }})
          git diff --quiet --exit-code README.md || git commit README.md -m "updating coverage in README.md"

      - name: Push Coverage Badge
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{github.ref}}

      - id: output-sha
        run: |
          if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref }}" == 'refs/heads/main' ]]; then
            sha=$(git rev-parse HEAD)
          else
            sha="${{ github.sha }}"
          fi
          echo "$sha"
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      - name: Coverage Quality Gate
        run: |
          echo "Quality Gate: checking test coverage is above threshold ..."
          echo "Threshold             : ${{ inputs.TESTCOVERAGE_THRESHOLD }}%"
          totalCoverage=`go tool cover -func=temp/coverage.out | grep 'total:' | grep -Eo '[0-9]+\.[0-9]+'`
          echo "Current test coverage : $totalCoverage %"
          totalInt=${totalCoverage%.*}
          if [ "$totalInt" -ge "${{ inputs.TESTCOVERAGE_THRESHOLD }}" ]; then
              echo "OK"
          else
              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
              echo "Failed"
              exit 1
          fi

      - name: Run Server
        if: ${{ inputs.POSTMAN_ENABLED }}
        run: |
          GOFR_ENV=test go run main.go &
          sleep 60

      - name: Install newman and Run Postman Collection
        if: ${{ inputs.POSTMAN_ENABLED }}
        run: |
          npm install -g newman
          newman run postman-collections/${{ inputs.APP_NAME }}.postman-collection.json

      - name: Stop Server
        if: ${{ inputs.POSTMAN_ENABLED }}
        run: pkill main
