name: "code_quality"
on:
  workflow_call:
    inputs:
      DOCKER_FILE_PATH:
        description: 'path for main file'
        required: true
        type: string
    secrets:
      PAT:
        description: 'pat of the stage'
        required: true

        
jobs:
  code_quality:
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/zopsmart/gha-images:go-0.1.1
        options: --rm
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v3

        - name: Setup Git
          run: |
            git config --global url."https://${{ secrets.PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
            git config --global http.sslVerify false

        - name: change directory
          run: cd ${{ inputs.DOCKER_FILE_PATH }}

        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.54.2
            args: --timeout 8m