name: "stage deploy"
on:
  workflow_call:
    inputs:
      CLUSTER_NAME:
        description: 'required input'
        required: true
        type: string

      CLUSTER_PROJECT:
        description: 'required input'
        required: true
        type: string

      NAMESPACE:
        description: 'required input'
        required: true
        type: string

      registry:
        description: 'required input'
        required: true
        type: string

      username:
        description: 'required input'
        required: true
        type: string

      GCR_PROJECT:
        description: 'required input'
        required: true
        type: string

      APP_NAME:
        description: 'required input'
        required: true
        type: string

      DOCKER_FILE_PATH:
        description: 'path of docker file'
        required: true
        type: string

      GO_VERSION:
        description: 'go version'
        required: false
        type: string
        default: '1.20'

      EXTRA_DEPENDENCIES:
        description: 'enable step to install extra dependencies'
        required: false
        type: boolean
        default: false

      DEPENDENCIES_COMMAND:
        description: 'commands to install extra dependencies'
        required: false
        type: string

      BUILD_COMMAND:
        description: 'go build command'
        required: true
        type: string

      ARTIFACT_PATH:
        description: "path used for build with respect to main.go file"
        required: true
        type: string
      SHA:
        type: string
        required: true
      TYPE:
        type: string
        description: "deployment or cron"
        required: false
        default: deployment
      BUILD_ARGUMENTS:
        description: 'build arguments for DockerFile'
        required: false
        type: string
      ENV_FILE_PATH:
        description: 'env file path'
        required: false
        type: string
        default: "./configs/.stage.env"

    secrets:
      PAT:
        description: 'required input'
        required: false
      GCR_KEY:
        description: 'required input'
        required: true
      DEPLOY_KEY:
        description: 'required input'
        required: true



jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main') && (github.event_name == 'push')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '${{ inputs.GO_VERSION }}'

      - name: Get dependencies
        run: |
          git config --global url."https://${{ secrets.PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global http.sslVerify false
          go mod download

      - name: Extra dependencies
        if: ${{ inputs.EXTRA_DEPENDENCIES }}
        run: |
          ${{ inputs.DEPENDENCIES_COMMAND }}

      - name: Make Directory
        run: mkdir build

      - name: Build
        run: |
          cd ${{ inputs.DOCKER_FILE_PATH }}
          ls
          pwd
          ${{ inputs.BUILD_COMMAND }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.APP_NAME }}
          path: ${{ inputs.DOCKER_FILE_PATH }}/${{ inputs.ARTIFACT_PATH }}

  dockerize:
    name: 🐳 Dockerize Stage
    runs-on: ubuntu-latest
    needs: [ build ]
    outputs:
      image: ${{ steps.output-image.outputs.image }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.APP_NAME }}


      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.GCR_KEY }}

      - name: Build and Push Docker Image to GCR
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ${{ inputs.DOCKER_FILE_PATH }}/Dockerfile
          tags: ${{ inputs.registry }}/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ inputs.SHA }}
          build-args: |
            ${{ inputs.BUILD_ARGUMENTS }}
      - id: output-image
        run: echo "image=`echo ${{ inputs.registry }}/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ inputs.SHA }}`" >> "$GITHUB_OUTPUT"

  update_configmap:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main')
    uses: zopsmart/zs-workflows/.github/workflows/update-configmap.yaml@main
    with:
      APP_NAME: ${{ inputs.APP_NAME }}
      ENV_FILE_PATH: ${{ inputs.ENV_FILE_PATH }}
      CLUSTER_PROJECT: ${{ inputs.CLUSTER_PROJECT }}
      CLUSTER_NAME: ${{ inputs.CLUSTER_NAME }}
      NAMESPACE: ${{ inputs.NAMESPACE }}
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

  stage_deployment:
    runs-on: ubuntu-latest
    needs: dockerize
    if: (github.ref == 'refs/heads/main') && (github.event_name == 'push')
    container:
      image: ghcr.io/zopsmart/gha-images:deployments-0.1.3
      options: --rm
    name: 🚀 Deploy Stage
    env:
      image: ${{needs.dockerize.outputs.image}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify
        run: ls -la

      - name: Directory
        run: pwd

      - name: Authorize to GCP service account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DEPLOY_KEY }}

      - name: Set GCloud Project and Fetch Cluster Credentials
        run: gcloud container clusters get-credentials ${{ inputs.CLUSTER_NAME }}  --region=us-central1 --project=${{ inputs.CLUSTER_PROJECT }}

      - name: Update Deployment Image
        if: ${{ inputs.TYPE == 'deployment' }}
        run: kubectl set image deployment/${{ inputs.APP_NAME }} ${{ inputs.APP_NAME }}=${{ env.image }} --namespace ${{ inputs.NAMESPACE }}

      - name: Update Cron Image
        if: ${{ inputs.TYPE == 'cron' }}
        run: kubectl set image cronjobs/${{ inputs.APP_NAME }} ${{ inputs.APP_NAME }}=${{ env.image }} --namespace ${{ inputs.NAMESPACE }}
