name: "prod deploy"
on:
  workflow_call:
    inputs:
      CLUSTER_NAME:
        description: 'required input'
        required: true
        type: string

      CLUSTER_PROJECT:
        description: 'required input'
        required: true
        type: string

      NAMESPACE:
        description: 'required input'
        required: true
        type: string

      registry:
        description: 'required input'
        required: true
        type: string

      username:
        description: 'required input'
        required: true
        type: string

      GCR_PROJECT:
        description: 'required input'
        required: true
        type: string

      APP_NAME:
        description: 'required input'
        required: true
        type: string

      TYPE:
        type: string
        description: "deployment or cron"
        required: false
        default: deployment

    secrets:
      GCR_KEY:
        description: 'required input'
        required: true
      DEPLOY_KEY:
        description: 'required input'
        required: true



jobs:
  check-tag:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v')}}
    outputs:
      tag_exists: ${{ steps.tag-check.outputs.tag_exists }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.CLUSTER_PROJECT }}
          service_account_key: ${{ secrets.GCR_KEY }}
          export_default_credentials: true

      - name: Check if tag exists
        id: tag-check
        run: |
          if gcloud container images describe ${{ inputs.registry }}/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ github.sha }} 2>/dev/null; then
              echo "tag_exists=true" >> "$GITHUB_OUTPUT"
          else
              echo "tag_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Print commit has value
        run: |
          echo "${{ github.sha }}"

      - name: Print tag_exists value
        run: |
          echo "${{ steps.tag-check.outputs.tag_exists }}"
          

  dockerize:
    runs-on: ubuntu-latest
    needs: check-tag
    if: ${{ needs.check-tag.outputs.tag_exists == 'true' }}
    outputs:
      image: ${{ steps.output-image.outputs.image }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.GCR_KEY }}


      - name: Re tag and Push Docker Image to GCR
        run: | 
          docker pull gcr.io/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ github.sha }}
          docker tag gcr.io/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ github.sha }} gcr.io/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ env.RELEASE_VERSION }}
          docker push gcr.io/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ env.RELEASE_VERSION }}
      - id: output-image
        run: echo "image=`echo gcr.io/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ env.RELEASE_VERSION }}`" >> "$GITHUB_OUTPUT"

  update_configmap:
    uses: zopsmart/zs-workflows/.github/workflows/update-configmap.yaml@main
    with:
      APP_NAME: ${{ inputs.APP_NAME }}
      ENV_FILE_PATH: ./configs/.prod.env
      CLUSTER_PROJECT: ${{ inputs.CLUSTER_PROJECT }}
      CLUSTER_NAME: ${{ inputs.CLUSTER_NAME }
      NAMESPACE: ${{ inputs.NAMESPACE }}
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

  prod_deployment:
    runs-on: ubuntu-latest
    needs: dockerize
    container:
      image: ghcr.io/zopsmart/gha-images:deployments-0.1.3
      options: --rm
    name: 🚀 Deploy Prod
    env:
      image: ${{needs.dockerize.outputs.image}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify
        run: ls -la

      - name: Directory
        run: pwd

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ inputs.CLUSTER_PROJECT }}
          service_account_key: ${{ secrets.DEPLOY_KEY }}
          export_default_credentials: true

      - name: Extract Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set GCloud Project and Fetch Cluster Credentials
        run: gcloud container clusters get-credentials ${{ inputs.CLUSTER_NAME }}  --region=us-central1 --project=${{ inputs.CLUSTER_PROJECT }}

      - name: Set App Version
        if: ${{ inputs.TYPE == 'deployment' }}
        run: kubectl set env deployment/${{ inputs.APP_NAME }} APP_VERSION=${{ env.RELEASE_VERSION }} --namespace ${{ inputs.NAMESPACE }}

      - name: Update Deployment Image
        if: ${{ inputs.TYPE == 'deployment' }}
        run: kubectl set image deployment/${{ inputs.APP_NAME }} ${{ inputs.APP_NAME }}=${{ env.image }} --namespace ${{ inputs.NAMESPACE }}

      - name: Update Cron Image
        if: ${{ inputs.TYPE == 'cron' }}
        run: kubectl set image cronjobs/${{ inputs.APP_NAME }} ${{ inputs.APP_NAME }}=${{ env.image }} --namespace ${{ inputs.NAMESPACE }}
