name: "stage deploy"
on:
  workflow_call:
    inputs:
      CLUSTER_NAME:
        description: 'required input'
        required: true
        type: string

      CLUSTER_PROJECT:
        description: 'required input'
        required: true
        type: string

      NAMESPACE:
        description: 'required input'
        required: true
        type: string

      registry:
        description: 'required input'
        required: true
        type: string

      username:
        description: 'required input'
        required: true
        type: string

      GCR_PROJECT:
        description: 'required input'
        required: true
        type: string

      APP_NAME:
        description: 'required input'
        required: true
        type: string

      DOCKER_FILE_PATH:
        description: 'path of docker file'
        required: true
        type: string

      BUILD_COMMAND:
        description: 'go build command'
        required: true
        type: string

      ARTIFACT_PATH:
        description: "path used for build with respect to main.go file"
        required: true
        type: string
      SHA:
        type: string
        required: true
      TYPE:
        type: string
        description: "deployment or cron"
        required: false
        default: deployment

    secrets:
      PAT:
        description: 'required input'
        required: false
      GCR_KEY:
        description: 'required input'
        required: true
      DEPLOY_KEY:
        description: 'required input'
        required: true
        


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zopsmart/gha-images:go-0.1.1
      options: --rm
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          git config --global url."https://${{ secrets.PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global http.sslVerify false
          go mod download

      - name: Make Directory
        run: mkdir build

      - name: Build
        run: |
          cd ${{ inputs.DOCKER_FILE_PATH }}
          ls
          pwd
          ${{ inputs.BUILD_COMMAND }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.APP_NAME }}
          path: ${{ inputs.DOCKER_FILE_PATH }}/${{ inputs.ARTIFACT_PATH }}

  dockerize:
    runs-on: ubuntu-latest
    needs: [ build ]
    outputs:
      image: ${{ steps.output-image.outputs.image }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.APP_NAME }}


      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.GCR_KEY }}


      - name: Build and Push Docker Image to GCR
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ${{ inputs.DOCKER_FILE_PATH }}/Dockerfile
          tags: gcr.io/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ inputs.SHA }}
      - id: output-image
        run: echo "image=`echo gcr.io/${{ inputs.GCR_PROJECT }}/${{ inputs.APP_NAME }}:${{ inputs.SHA }}`" >> "$GITHUB_OUTPUT"

  stage_deployment:
      runs-on: ubuntu-latest
      needs: dockerize
      container:
        image: ghcr.io/zopsmart/gha-images:deployments-0.1.2
        options: --rm
      name: 🚀 Deploy Stage
      env:
        image: ${{needs.dockerize.outputs.image}}

      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Verify
          run: ls -la
          
        - name: Directory
          run: pwd

        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ inputs.CLUSTER_PROJECT }}
            service_account_key: ${{ secrets.DEPLOY_KEY }}
            export_default_credentials: true

        - name: Set GCloud Project and Fetch Cluster Credentials
          run: gcloud container clusters get-credentials ${{ inputs.CLUSTER_NAME }}  --region=us-central1 --project=${{ inputs.CLUSTER_PROJECT }}

        - name: Update Deployment Image
          if: ${{ inputs.TYPE == 'deployment' }}
          run: kubectl set image deployment/${{ inputs.APP_NAME }} ${{ inputs.APP_NAME }}=${{ env.image }} --namespace ${{ inputs.NAMESPACE }}

        - name: Update Cron Image
          if: ${{ inputs.TYPE == 'cron' }}
          run: kubectl set image cronjobs/${{ inputs.APP_NAME }} ${{ inputs.APP_NAME }}=${{ env.image }} --namespace ${{ inputs.NAMESPACE }}