name: "checkout and build"
on:
  workflow_call:
    inputs:
      JDK_VERSION:
        description: 'jdk version'
        required: false
        type: string
        default: '11.0.10'
    secrets:
      GAR_SECRET:
        description: 'required input'
        required: true


jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main') || github.event.review.state == 'approved'
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '${{ inputs.JDK_VERSION }}'
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setting Project ID as env
        run: |
          echo '${{ secrets.GAR_SECRET }}' > credentials.json
          PROJECT_ID=$(jq -r '.project_id' credentials.json)
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Authorize to GCP service account to pull rocket packages from GAR
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GAR_SECRET }}

      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: build/libs