name: "test and linters"
on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
         description: 'github token'
         required: true
    inputs:
      APP_NAME:
          description: 'name of ui service'
          required: true
    outputs:
      SHA:
        description: "commit sha for image"
        value: ${{ jobs.build.outputs.sha }}


jobs:
  build:
    runs-on: ubuntu-latest
    name: 🧪 Test and 🔨 Build
    outputs:
      sha: ${{ steps.output-sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: installing dependencies and zipping node modules
        run: |
          echo "@zopsmart:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PAT }}" >> ~/.npmrc
          yarn install
          tar -zcf node_modules.zip node_modules/

      - name: run linter
        run: |
          CI=false yarn lint

      - name: run prettier
        run: |
          CI=false yarn prettier:check

      - name: run tests
        run: |
          CI=false yarn test:coverage

      - name: Generate Coverage Badges
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          CI=false yarn make-badges

      - name: Commit Badge changes
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet --exit-code README.md || git commit -a -m "Update badges in README.md file"
      

      - name: Push Coverage Badge
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{github.ref}}

      - id: output-sha
        run: |
          if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref }}" == 'refs/heads/main' ]]; then
            sha=$(git rev-parse HEAD)
          else
            sha="${{ github.sha }}"
          fi
          echo "$sha"
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      - name: Generating build
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          CI=false yarn run build
          tar -zcf ${{ inputs.APP_NAME }}.zip build

      - uses: actions/upload-artifact@v3
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
        name: upload zipped build and node modules
        with:
          name: artifacts
          path: |
            ${{ inputs.APP_NAME }}.zip
            node_modules.zip