name: "stage deploy"
on:
  workflow_call:
    inputs:
      APP_NAME:
        type: string
        required: true
      IMAGE_REGISTRY:
        type: string
        required: true
      GAR_PROJECT:
        type: string
        required: true
      GAR_REGISTRY:
        type: string
        required: true
      CLUSTER_PROJECT:
        type: string
        required: true
      CLUSTER_NAME:
        type: string
        required: true
      NAMESPACE:
        type: string
        required: true
      HELM_VALUES_PATH:
        type: string
        required: true
      DOCKER_FILE_PATH:
        description: 'path of docker file'
        required: true
        type: string
      UNZIP_COMMAND:
        required: true
        type: string
      CREATE_NPMRC:
        required: false
        type: boolean
        default: false

      SHA:
        type: string
        required: true

      BUILD_ARGUMENTS:
        description: 'build arguments for DockerFile'
        required: false
        type: string

      ENV_FILE_PATH:
        description: 'env file path'
        required: false
        type: string
        default: "./configs/.stage.env"

    secrets:
      PAT:
        description: 'required input'
        required: true
      GAR_KEY:
        description: 'required input'
        required: true
      NPM_TOKEN:
        description: 'npm token'
        required: false



jobs:
  dockerize_stage:
    name: 🐳 Dockerize Stage
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development') && (github.event_name == 'push')
    outputs:
      image: ${{ steps.output-image.outputs.image }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.IMAGE_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GAR_KEY }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.APP_NAME }}

      - name: Create .npmrc File
        if: ${{ inputs.CREATE_NPMRC }}
        run: |
          echo "@zopsmart:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Unzipping artifacts
        id: tag
        run: |
          ${{ inputs.UNZIP_COMMAND }}

      - name: Build and Push Docker Image to gar
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ${{ inputs.DOCKER_FILE_PATH }}/Dockerfile
          tags:  ${{ inputs.IMAGE_REGISTRY }}/${{ inputs.GAR_PROJECT }}/${{ inputs.GAR_REGISTRY }}/${{ inputs.APP_NAME }}:${{ inputs.SHA }}
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            ${{ inputs.BUILD_ARGUMENTS }}
      - id: output-image
        run: echo "image=`echo  ${{ inputs.IMAGE_REGISTRY }}/${{ inputs.GAR_PROJECT }}/${{ inputs.GAR_REGISTRY }}/${{ inputs.APP_NAME }}:${{ inputs.SHA }}`" >> "$GITHUB_OUTPUT"

  update_configmap:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/development')
    uses: zopsmart/zs-workflows/.github/workflows/update-configmap.yaml@main
    with:
      APP_NAME: ${{ inputs.APP_NAME }}
      ENV_FILE_PATH: ${{ inputs.ENV_FILE_PATH }}
      CLUSTER_PROJECT: ${{ inputs.CLUSTER_PROJECT }}
      CLUSTER_NAME: ${{ inputs.CLUSTER_NAME }}
      NAMESPACE: ${{ inputs.NAMESPACE }}
    secrets:
      DEPLOY_KEY: ${{ secrets.GAR_KEY }}

  stage_deployment:
    runs-on: ubuntu-latest
    name: 🚀 Deploy Stage
    needs: dockerize_stage
    if: (github.ref == 'refs/heads/development')
    container:
      image: ghcr.io/zopsmart/gha-images:deployments-0.1.3
      options: --rm
    env:
      image: ${{needs.dockerize_stage.outputs.image}}

    steps:
      - uses: actions/checkout@v4

      - name: Add Helm Repo
        run: |
          helm repo add helm \
            --username "${{ github.actor }}" \
            --password "${{ secrets.PAT }}" \
            "https://raw.githubusercontent.com/zopsmart/helm/main/charts"

      - name: Authorize to GCP service account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GAR_KEY }}

      - name: Set GCloud Project and Fetch Cluster Credentials
        run: gcloud container clusters get-credentials ${{ inputs.CLUSTER_NAME }} --region=us-central1 --project=${{ inputs.CLUSTER_PROJECT }}

      - name: Update Deployment Image
        run: helm upgrade --install --set image=${{ env.image }} ${{ inputs.APP_NAME }} helm/service -f ${{ inputs.HELM_VALUES_PATH }} -n ${{ inputs.NAMESPACE }} --version v0.1.4
