name: 🧪 Test, 🔨 Build, and 🐳 Dockerize
on:
  workflow_call:
    outputs:
      SHA:
        description: "commit sha for image"
        value: ${{ jobs.test.outputs.sha }}
    secrets:
      PAT:
        description: 'github token'
        required: true
      NPM_TOKEN:
        description: 'npm token'
        required: false
      GAR_SECRET:
        description: 'gar key'
        required: false
    inputs:
      APP_NAME:
        description: 'name of ui service'
        required: true
        type: string
      NODE_VERSION:
        description: 'node version'
        type: string
        required: true
      TEST_COMMAND:
        description: 'command to run test files'
        required: false
        type: string
      BRANCH_NAME:
        description: 'name of branch main/master'
        required: false
        type: string
        default: main
      LINTER_CHECKS:
        required: false
        type: boolean
        default: true
      ENABLE_TESTS:
        required: false
        type: boolean
        default: true
      PRETTIER_CHECKS:
        required: false
        type: boolean
        default: true
      USE_GAR_PKG:
        description: 'whether to fetch pacakages from GAR'
        required: false
        type: boolean
        default: false

env:
  event_flag: ${{ github.event_name == 'push' }}
  branch_flag: ${{ github.ref == 'refs/heads/${{ inputs.BRANCH_NAME }}' }}
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ (github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'  || github.event.review.state == 'approved') && !startsWith(github.ref, 'refs/tags/v') }}
    name: 🧪 Test, 🔨 Build and 🐳 Dockerize
    outputs:
      sha: ${{ steps.output-sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Authorize to GCP service account to pull rocket packages from GAR
        if: ${{ inputs.USE_GAR_PKG }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GAR_SECRET }}

      - name: installing dependencies and zipping node modules
        run: |
          if [[ "${{ inputs.USE_GAR_PKG }}" == "true" ]]; then
            echo '${{ secrets.GAR_SECRET }}' > credentials.json
            PROJECT_ID=$(jq -r '.project_id' credentials.json)
            ACCESS_TOKEN=$(gcloud auth print-access-token)
            echo "@zopsmart:registry=https://us-central1-npm.pkg.dev/${PROJECT_ID}/npm-packages/" >> ~/.npmrc
            echo "//us-central1-npm.pkg.dev/${PROJECT_ID}/npm-packages/:_authToken=${ACCESS_TOKEN}" >> ~/.npmrc
            rm -rf credentials.json
          else
            echo "@zopsmart:registry=https://npm.pkg.github.com/" >> ~/.npmrc
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          fi
          yarn install
          tar -zcf node_modules.zip node_modules/

      - name: run linter
        if: ${{ inputs.LINTER_CHECKS }}
        run: |
          CI=false yarn lint

      - name: run prettier
        if: ${{ inputs.PRETTIER_CHECKS }}
        run: |
          CI=false yarn prettier:check

      - name: run tests
        if: ${{ inputs.ENABLE_TESTS  }}
        run: |
          ${{ inputs.TEST_COMMAND }}

      - name: Generate Coverage Badges
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main') && (inputs.ENABLE_TESTS) }}
        run: |
          CI=false yarn make-badges

      - name: Commit Badge changes
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main') && (inputs.ENABLE_TESTS) }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet --exit-code README.md || git commit -a -m "Update badges in README.md file"


      - name: Push Coverage Badge
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main') && (inputs.ENABLE_TESTS) }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}

      - name: Latest Commit Hash
        id: output-sha
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development') && (github.event_name == 'push')
        run: |
          if [ "${{ github.event_name }}" == 'push' ] && [ \( "${{ github.ref }}" = 'refs/heads/main' \) ]; then
            sha=$(git rev-parse HEAD)
          else
            sha="${{ github.sha }}"
          fi
          echo "$sha"
          echo "sha=$sha" >> "$GITHUB_OUTPUT"